// AUTH
export const FETCH_AUTH = 'FETCH_AUTH'
export const RECEIVE_AUTH = 'RECEIVE_AUTH'
export const SUCCESS_AUTH = 'SUCCESS_AUTH'
export const FAILED_AUTH = 'FAILED_AUTH'

// IMAGE
export const FETCH_IMAGE = 'FETCH_IMAGE'
export const SUCCESS_IMAGE = 'SUCCESS_IMAGE'
export const FAILED_IMAGE = 'FAILED_IMAGE'

// STORE
export const FETCH_STORE = 'FETCH_STORE'
export const RECEIVE_STORE = 'RECEIVE_STORE'
export const FAILED_STORE = 'FAILED_STORE'
export const UPDATE_STATE_STORE = 'UPDATE_STATE_STORE'
export const SUCCESS_STORE = 'SUCCESS_STORE'
export const RECEIVE_ITEM_STORE = 'RECEIVE_ITEM_STORE'
export const RESET_LIST_STORE = 'RESET_LIST_STORE'
export const RECEIVE_STORE_DROPDOWN = 'RECEIVE_STORE_DROPDOWN'

// BANK
export const FETCH_BANK = 'FETCH_BANK'
export const FAILED_BANK = 'FAILED_BANK'
export const RECEIVE_BANK_DROPDOWN = 'RECEIVE_BANK_DROPDOWN'

// COURIER
export const FETCH_COURIER = 'FETCH_COURIER'
export const RECEIVE_COURIER = 'RECEIVE_COURIER'
export const FAILED_COURIER = 'FAILED_COURIER'

// USER
export const FETCH_USER = 'FETCH_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_ITEM_USER = 'RECEIVE_ITEM_USER'
export const SUCCESS_USER = 'SUCCESS_USER'
export const FAILED_USER = 'FAILED_USER'
export const UPDATE_STATE_USER = 'UPDATE_STATE_USER'
export const RESET_LIST_USER = 'RESET_LIST_USER'

// PROMO
export const FETCH_PROMO = 'FETCH_PROMO'
export const RECEIVE_PROMO = 'RECEIVE_PROMO'
export const RECEIVE_PROMO_SLIDER = 'RECEIVE_PROMO_SLIDER'
export const RECEIVE_ITEM_PROMO = 'RECEIVE_ITEM_PROMO'
export const SUCCESS_PROMO = 'SUCCESS_PROMO'
export const FAILED_PROMO = 'FAILED_PROMO'
export const UPDATE_STATE_PROMO = 'UPDATE_STATE_PROMO'
export const RESET_LIST_PROMO = 'RESET_LIST_PROMO'

// HELP
export const FETCH_HELP = 'FETCH_HELP'
export const RECEIVE_HELP = 'RECEIVE_HELP'
export const FAILED_HELP = 'FAILED_HELP'

// HELP DETAIL
export const FETCH_HELP_DETAIL = 'FETCH_HELP_DETAIL'
export const RECEIVE_HELP_DETAIL = 'RECEIVE_HELP_DETAIL'
export const FAILED_HELP_DETAIL = 'FAILED_HELP_DETAIL'

// BUNDLE
export const FETCH_BUNDLE = 'FETCH_BUNDLE'
export const RECEIVE_ALL_BUNDLE = 'RECEIVE_ALL_BUNDLE'
export const RECEIVE_BUNDLE = 'RECEIVE_BUNDLE'
export const RECEIVE_ITEM_BUNDLE = 'RECEIVE_ITEM_BUNDLE'
export const FAILED_BUNDLE = 'FAILED_BUNDLE'
export const UPDATE_STATE_BUNDLE = 'UPDATE_STATE_BUNDLE'
export const RESET_LIST_BUNDLE = 'RESET_LIST_BUNDLE'

// PRODUCT
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'
export const FAILED_PRODUCT = 'FAILED_PRODUCT'

// PRODUCT CATEGORY
export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY'
export const RECEIVE_PRODUCT_CATEGORY = 'RECEIVE_PRODUCT_CATEGORY'
export const RECEIVE_CURRENT_PRODUCT_CATEGORY = 'RECEIVE_CURRENT_PRODUCT_CATEGORY'
export const RESET_LIST_PRODUCT_CATEGORY = 'RESET_LIST_PRODUCT_CATEGORY'
export const UPDATE_STATE_PRODUCT_CATEGORY = 'UPDATE_STATE_PRODUCT_CATEGORY'
export const FAILED_PRODUCT_CATEGORY = 'FAILED_PRODUCT_CATEGORY'

// USER ADDRESS
export const FETCH_ADDRESS = 'FETCH_ADDRESS'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const SUCCESS_ADDRESS = 'SUCCESS_ADDRESS'
export const FAILED_ADDRESS = 'FAILED_ADDRESS'

// LOCAL TRANSACTION
export const RECEIVE_CART_DETAIL_LOCAL_TRANSACTION = 'RECEIVE_CART_DETAIL_LOCAL_TRANSACTION'
export const RECEIVE_PHOTO_LIST = 'RECEIVE_PHOTO_LIST'
export const RECEIVE_PHOTO_DETAIL_LOCAL_TRANSACTION = 'RECEIVE_PHOTO_DETAIL_LOCAL_TRANSACTION'
export const RECEIVE_LOCAL_TRANSACTION = 'RECEIVE_LOCAL_TRANSACTION'
export const FAILED_LOCAL_TRANSACTION = 'FAILED_LOCAL_TRANSACTION'

// TRANSACTION
export const FETCH_TRANSACTION = 'FETCH_TRANSACTION'
export const RECEIVE_ITEM_TRANSACTION = 'RECEIVE_ITEM_TRANSACTION'
export const SUCCESS_TRANSACTION = 'SUCCESS_TRANSACTION'
export const RECEIVE_TRANSACTION = 'RECEIVE_TRANSACTION'
export const UPDATE_NUMBER_PHOTOS = 'UPDATE_NUMBER_PHOTOS'
export const UPDATE_PROGRESS_UPLOAD = 'UPDATE_PROGRESS_UPLOAD'
export const UPDATE_STATE_TRANSACTION = 'UPDATE_STATE_TRANSACTION'
export const RESET_LIST_TRANSACTION = 'RESET_LIST_TRANSACTION'
export const FAILED_TRANSACTION = 'FAILED_TRANSACTION'

// COUNT TRANSACTION
export const FETCH_COUNT_TRANSACTION = 'FETCH_COUNT_TRANSACTION'
export const RECEIVE_COUNT_TRANSACTION = 'RECEIVE_COUNT_TRANSACTION'
export const RESET_COUNT_TRANSACTION = 'RESET_COUNT_TRANSACTION'
export const FAILED_COUNT_TRANSACTION = 'FAILED_COUNT_TRANSACTION'

// COMPLAIN
export const FETCH_COMPLAIN = 'FETCH_COMPLAIN'
export const SUCCESS_COMPLAIN = 'SUCCESS_COMPLAIN'
export const FAILED_COMPLAIN = 'FAILED_COMPLAIN'

// COMPLAIN HISTORY
export const FETCH_COMPLAIN_HISTORY = 'FETCH_COMPLAIN'
export const RECEIVE_COMPLAIN_HISTORY = 'RECEIVE_COMPLAIN_HISTORY'
export const FAILED_COMPLAIN_HISTORY = 'FAILED_COMPLAIN'

// TRACKING SHIPPING
export const FETCH_TRACKING_SHIPPING = 'FETCH_TRACKING_SHIPPING'
export const RECEIVE_TRACKING_SHIPPING = 'RECEIVE_TRACKING_SHIPPING'
export const FAILED_TRACKING_SHIPPING = 'FAILED_TRACKING_SHIPPING'
